Repository rte-antares-rpackage/antaresRead, pull requests merged in 2024-03, with the labels that each got.

#238 readBindingConstraints() minor fix to read BC v870 from API
  R/readBindingConstraints.R
Labels: bug

#237 Replace stop by warning readClusterDesc
  NEWS.md
  R/readClusterDesc.R
Labels: bug

#239 api_put() update to return server description + exception message
  R/API-methods.R
Labels: next_release

#241 fix bug readClusterDesc when no cluster + cover ST and RES case
  NEWS.md
  R/readClusterDesc.R
Labels: bug, enhancement
