Repository rte-antares-rpackage/antaresRead, pull requests merged in 2025-03, with the labels that each got.

#276 Default API timeout to 600
  NEWS.md
  R/API-methods.R
  R/setSimulationPathAPI.R
  man/setSimulationPath.Rd
Labels: feature

#278 Enable or disable the time series reading in readBindingConstraints()
  DESCRIPTION
  NEWS.md
  R/readBindingConstraints.R
  man/readBindingConstraints.Rd
  tests/testthat/test-readBindingConstraints.R
Labels: feature

#279 Fix setSimulationPath() version number returned
  DESCRIPTION
  NEWS.md
  R/setSimulationPath.R
  tests/testthat/test-setSimulationPath.R
Labels: bug

#285 Read storage cluster properties v9.2
  NEWS.md
  R/readClusterDesc.R
  R/zzz.R
  inst/referential_properties/cluster_properties.csv
  inst/referential_properties/properties_input_renewable.csv
  inst/referential_properties/properties_input_storage.csv
  inst/referential_properties/properties_input_storage_test.csv
  inst/referential_properties/properties_input_thermal.csv
  man/readClusterDesc.Rd
  tests/testthat/test-readClusterDesc.R
Labels: release
