Repository rte-antares-rpackage/antaresRead, pull requests merged in 2025-04, with the labels that each got.

#286 readInputTS() add test to read well new TS
  NEWS.md
  R/importInput.R
  tests/testthat/test-readInputTS.R
Labels: release

#284 Release Antares Simulator v9.2 [MAIN branch]
  DESCRIPTION
  NEWS.md
  R/importInput.R
  R/readClusterDesc.R
  R/zzz.R
  _pkgdown.yml
  inst/referential_properties/cluster_properties.csv
  inst/referential_properties/properties_input_renewable.csv
  inst/referential_properties/properties_input_storage.csv
  inst/referential_properties/properties_input_storage_test.csv
  inst/referential_properties/properties_input_thermal.csv
  man/readClusterDesc.Rd
  revdep/README.md
  tests/testthat/test-readClusterDesc.R
  tests/testthat/test-readInputTS.R
Labels: release

#287 Argument areas is not set to all if argument clustersRes is not null
  NEWS.md
  R/readAntares.R
  tests/testthat/test-readAntares.R
Labels: bug

#282 Move comments property from coefs to properties in binding constraints object
  NEWS.md
  R/readBindingConstraints.R
  tests/testthat/test-readBindingConstraints.R
Labels: bug

#281 Search and read specific binding constraints by names
  NEWS.md
  R/readBindingConstraints.R
  man/dot-filter_bindingConstraints_by_names.Rd
  man/readBindingConstraints.Rd
  tests/testthat/test-readBindingConstraints.R
Labels: feature

#288 Expansion in output mode to fix setSimulationPath()
  NEWS.md
  R/setSimulationPath.R
Labels: bug
